apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkdocs
  template:
    metadata:
      labels:
        app: mkdocs
    spec:
      containers:
      - name: mkdocs-container
        image: nicoalba/mkdocs-devops
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mkdocs-service
spec:
  selector:
    app: mkdocs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
